version: '3.4'

services:
  rocketcv:
    image: ${DOCKER_REGISTRY-}rocketcv
    build:
      context: .
      dockerfile: RocketCV/Dockerfile
    depends_on:
        - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
